gateways:
  duckdb:
    connection:
      type: duckdb
      database: C:\workspace\solid-bassoon\crypto_tracker.duckdb
default_gateway: duckdb

model_defaults:
  dialect: duckdb
  start: 2026-01-01
  cron: '@daily'

linter:
  enabled: true
  rules: ["ambiguousorinvalidcolumn", "invalidselectstarexpansion"]

model_naming:
  infer_names: true

plan:
  enable_preview: true